import explore_input_diff
import time

print('Explore SIMON-32/64 nr8 input difference...')

print('- Hamming weight: 1')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=1, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_1_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 2')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=2, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_2_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 3')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=3, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_3_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 4')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=4, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_4_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 5')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=5, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_5_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 6')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=6, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_6_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 7')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=7, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_7_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 8')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=8, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_8_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 9')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=9, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_9_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 10')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=10, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_10_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 11')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=11, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_11_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')


print('- Hamming weight: 12')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=12, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_12_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 13')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=13, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_13_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 14')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=14, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_14_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 15')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=15, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_15_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 16')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=16, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_16_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 17')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=17, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_17_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 18')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=18, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_18_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 19')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=19, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_19_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 20')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=20, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_20_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 21')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=21, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_21_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 22')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=22, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_22_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 23')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=23, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_23_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 24')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=24, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_24_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 25')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=25, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_25_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 26')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=26, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_26_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 27')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=27, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_27_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 28')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=28, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_28_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 29')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=29, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_29_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 30')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=30, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_30_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 31')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=31, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_31_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')

print('- Hamming weight: 32')
start_time = time.time()
explore_input_diff.explore_input_difference(alg='simon_32_64', blocksize=32, wordsize=16, nr=8, datasize=100000, hamming_weight=32, t0=0.002, t1=2, n_components=2, savepath="./explore_results/simon_32_64_nr8_hw_32_ver2.txt")
end_time = time.time()
print(f'  * Elapsed time: {end_time - start_time} sec')
